version: '3.7'

services:
  octoprint:
    restart: always
    build: .
    ports:
      - 5000:5000
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    volumes:
     - octoprint:/home/octoprint
  mjpg-streamer:
    restart: unless-stopped
    image: openhorizon/mjpg-streamer-pi3
    command: ./mjpg_streamer -o "output_http.so -w ./www" -i "input_uvc.so -r 1280x720 -d /dev/video0 -f 15"
    devices:
      - /dev/video0:/dev/video0
    ports:
      - 8080:8080
volumes:
  octoprint:

