version: '3.7'

services:
  octoprint:
    restart: always
    build: .
    ports:
      - 5000:5000
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    volumes:
     - octoprint:/home/octoprint

volumes:
  octoprint:
